name: CI-Test

env:
  CI: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master"]
jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24

      - name: Grant execute permission for Maven
        run: chmod +x ./mvnw

      - name: Run tests
        run: ./mvnw clean test